using UnityEngine; 
using System.Collections;
using System.Collections.Generic;

/**
 * Creates a grid of specified dimensions and generates a procedural maze using a
 * modified form of Prim's Algorithm.
 * @author Timothy Sesler
 * @author tds45
 * @date 4 February 2014
 * 
 * Adapted from work provided online by Austin Takechi 
 * Contact: MinoruTono@Gmail.com
 */ 
public class GridCreator : MonoBehaviour {
	
	public Transform CellPrefab;
	public Vector3 Size;
	public Transform[,] Grid;
	public Object[] Doodads; // prefab stuff to go in the maze
	public int torchspawnrate = 35; // spawn rate per cell
	public int monsterspawnrate = 5;
	public int weaponspawnrate = 10;
	public float GridHeight; // hight of walls
	public GameObject player; // the player
	public GameObject beam; // the beam of light
	public GameObject EndZone; // the end zone
	public static int Level = 1; // level player has reached
	public static bool levelstart;


	// Use this for initialization
	void Start () {
		player = GameObject.Find ("First Person Controller");
		player.SetActive (false);
		beam = GameObject.Find ("Spotlight");
		LevelStart ();
		levelstart = false;
	}

	public void LevelStart() {
		Size = new Vector3(3f * Level, 0, 3f * Level);
		CreateGrid();
		SetRandomNumbers();
		SetAdjacents();
		SetStart();
		FindNext ();
	}

	// Creates the grid by instantiating provided cell prefabs.
	void CreateGrid () {
		Grid = new Transform[(int)Size.x,(int)Size.z];

		// Places the cells and names them according to their coordinates in the grid.
		for (int x = 0; x < Size.x; x++) {
			for (int z = 0; z < Size.z; z++) {
				Transform newCell;
				newCell = (Transform)Instantiate(CellPrefab, new Vector3(x, 0, z), Quaternion.identity);
				newCell.name = string.Format("({0},0,{1})", x, z);
				newCell.parent = transform;
				newCell.GetComponent<CellScript>().Position = new Vector3(x, 0, z);
				Grid[x,z] = newCell;
			}
		}

		// Centers the camera on the maze.
		// Feel free to adjust this as needed.
		//Camera.main.transform.position = Grid[(int)(Size.x / 2f),(int)(Size.z / 2f)].position + Vector3.up * 20f;
		//Camera.main.orthographicSize = Mathf.Max(Size.x * 0.55f, Size.z * 0.5f);
	}

	// Sets a random weight to each cell.
	void SetRandomNumbers () {
		foreach (Transform child in transform) {
			int weight = Random.Range(0,10);
			child.GetComponentInChildren<TextMesh>().text = weight.ToString();
			child.GetComponent<CellScript>().Weight = weight;
		}
	}

	// Determines the adjacent cells of each cell in the grid.
	void SetAdjacents () {
		for(int x = 0; x < Size.x; x++){
			for (int z = 0; z < Size.z; z++) {
				Transform cell;
				cell = Grid[x,z];
				CellScript cScript = cell.GetComponent<CellScript>();
				
				if (x - 1 >= 0) {
					cScript.Adjacents.Add(Grid[x - 1, z]);
				}
				if (x + 1 < Size.x) {
					cScript.Adjacents.Add(Grid[x + 1, z]);
				}
				if (z - 1 >= 0) {
					cScript.Adjacents.Add(Grid[x, z - 1]);
				}
				if (z + 1 < Size.z) {
					cScript.Adjacents.Add(Grid[x, z + 1]);
				}
				
				cScript.Adjacents.Sort(SortByLowestWeight);
			}
		}
	}

	// Sorts the weights of adjacent cells.
	// Check the link for more info on custom comparators and sorting.
	// http://msdn.microsoft.com/en-us/library/0e743hdt.aspx
	int SortByLowestWeight (Transform inputA, Transform inputB) {
		int a = inputA.GetComponent<CellScript>().Weight;
		int b = inputB.GetComponent<CellScript>().Weight;
		return a.CompareTo(b);
	}

	/*********************************************************************
	 * Everything after this point pertains to generating the actual maze.
	 * Look at the Wikipedia page for more info on Prim's Algorithm.
	 * http://en.wikipedia.org/wiki/Prim%27s_algorithm
	 ********************************************************************/ 
	public List<Transform> PathCells;			// The cells in the path through the grid.
	public List<List<Transform>> AdjSet;		// A list of lists representing available adjacent cells.
	/** Here is the structure:
	 *  AdjSet{
	 * 		[ 0 ] is a list of all the cells
	 *      that have a weight of 0, and are
	 *      adjacent to the cells in the path
	 *      [ 1 ] is a list of all the cells
	 *      that have a weight of 1, and are
	 * 		adjacent to the cells in the path
	 *      ...
	 *      [ 9 ] is a list of all the cells
	 *      that have a weight of 9, and are
	 *      adjacent to the cells in the path
	 * 	}
	 *
	 * Note: Multiple entries of the same cell
	 * will not appear as duplicates.
	 * (Some adjacent cells will be next to
	 * two or three or four other path cells).
	 * They are only recorded in the AdjSet once.
	 */  

	// Initializes the sets and the starting cell.
	void SetStart () {
		PathCells = new List<Transform>();
		AdjSet = new List<List<Transform>>();
		
		for (int i = 0; i < 10; i++) {
			AdjSet.Add(new List<Transform>());	
		}
		
		Grid[0, 0].renderer.material.color = Color.yellow;
		AddToSet(Grid[0, 0]);
	}

	// Adds a cell to the set of visited cells.
	void AddToSet (Transform cellToAdd) {
		PathCells.Add(cellToAdd);
		
		foreach (Transform adj in cellToAdd.GetComponent<CellScript>().Adjacents) {
			adj.GetComponent<CellScript>().AdjacentsOpened++;
			
			if (!PathCells.Contains(adj) && !(AdjSet[adj.GetComponent<CellScript>().Weight].Contains(adj))) {
				AdjSet[adj.GetComponent<CellScript>().Weight].Add(adj);
			}
		}
	}

	// Determines the next cell to be visited.
	void FindNext () {
		Transform next;

		do {
			bool isEmpty = true;
			int lowestList = 0;

			// We loop through each sub-list in the AdjSet list of lists, until we find one with a count of more than 0.
			// If there are more than 0 items in the sub-list, it is not empty.
			// We've found the lowest sub-list, so there is no need to continue searching.
			for (int i = 0; i < 10; i++) {
				lowestList = i;
				
				if (AdjSet[i].Count > 0) {
					isEmpty = false;
					break;
				}
			}

			// The maze is complete.
			if (isEmpty) { 
				Debug.Log("Generation completed in " + Time.timeSinceLevelLoad + " seconds."); 
				CancelInvoke("FindNext");
				PathCells[PathCells.Count - 1].renderer.material.color = Color.yellow;
				// place the beam above the end cell
				beam.transform.position = new Vector3 (PathCells[PathCells.Count - 1].transform.position.x, 7, PathCells[PathCells.Count -1].transform.position.z); 
				// place the trigger at the end cell
				EndZone.transform.position = (PathCells[PathCells.Count - 1].position);
				/*
				 * creates a wall along the souther side of the maze
				 */
				for (int x = 0; x < (int)Size.x+1; x++){
					Transform cell;
					cell = (Transform)Instantiate(CellPrefab, new Vector3(x,0,-1), Quaternion.identity);
					cell.renderer.material.color = Color.yellow;
					cell.transform.localScale = new Vector3 (1, GridHeight, 1);
					cell.transform.localPosition = 
						new Vector3(cell.transform.localPosition.x, GridHeight/2, cell.transform.localPosition.z);
					cell.GetComponentInChildren<TextMesh>().active = false;
				}
				/*
				 * creates a wall  along the northern side of the maze
				 */
				for (int x = 0; x < (int)Size.x+1; x++){
					Transform cell;
					cell = (Transform)Instantiate(CellPrefab, new Vector3(x,0,(int)Size.z), Quaternion.identity);
					cell.renderer.material.color = Color.yellow;
					cell.transform.localScale = new Vector3 (1, GridHeight, 1);
					cell.transform.localPosition = 
						new Vector3(cell.transform.localPosition.x, GridHeight/2, cell.transform.localPosition.z);
					cell.GetComponentInChildren<TextMesh>().active = false;
				}
				/*
				 * creates a wall along the western side of the maze
				 */
				for (int x = 0; x < (int)Size.z; x++){
					Transform cell;
					cell = (Transform)Instantiate(CellPrefab, new Vector3(-1,0,x), Quaternion.identity);
					cell.renderer.material.color = Color.yellow;
					cell.transform.localScale = new Vector3 (1, GridHeight, 1);
					cell.transform.localPosition = 
						new Vector3(cell.transform.localPosition.x, GridHeight/2, cell.transform.localPosition.z);
					cell.GetComponentInChildren<TextMesh>().active = false;
				}
				/*
				 * creates a wall along the eastern side of the maze
				 */
				for (int x = 0; x < (int)Size.z; x++){
					Transform cell;
					cell = (Transform)Instantiate(CellPrefab, new Vector3((int)Size.x,0,x), Quaternion.identity);
					cell.renderer.material.color = Color.yellow;
					cell.transform.localScale = new Vector3 (1, GridHeight, 1);
					cell.transform.localPosition = 
						new Vector3(cell.transform.localPosition.x, GridHeight/2, cell.transform.localPosition.z);
					cell.GetComponentInChildren<TextMesh>().active = false;
				}

				foreach (Transform cell in Grid) {
					// Removes displayed weight
					cell.GetComponentInChildren<TextMesh>().renderer.enabled = false;

					if (!PathCells.Contains(cell)) {
						// HINT: Try something here to make the maze 3D
						cell.renderer.material.color = Color.yellow;
						cell.transform.localScale = new Vector3 (1, GridHeight, 1);
						cell.transform.localPosition = 
							new Vector3(cell.transform.localPosition.x, GridHeight/2, cell.transform.localPosition.z);
						cell.GetComponentInChildren<TextMesh>().active = false;
					}
				}
				player.SetActive (true);
				return;
			}
			// If we did not finish, then:
			// 1. Use the smallest sub-list in AdjSet as found earlier with the lowestList variable.
			// 2. With that smallest sub-list, take the first element in that list, and use it as the 'next'.
			next = AdjSet[lowestList][0];
			// Since we do not want the same cell in both AdjSet and Set, remove this 'next' variable from AdjSet.
			AdjSet[lowestList].Remove(next);
		} while (next.GetComponent<CellScript>().AdjacentsOpened >= 2);	// This keeps the walls in the grid, otherwise Prim's Algorithm would just visit every cell

		// The 'next' transform's material color becomes yellow.
		next.renderer.material.color = Color.yellow;
		if (Random.Range (0, 100) < torchspawnrate) { //  spawn torch in cell
			Instantiate(Doodads[0], new Vector3(next.position.x - .5f, next.position.y + .75f, next.position.z - .5f), Quaternion.Euler (25f, 0f ,-25f));		
		}
		if (Random.Range (0, 100) < monsterspawnrate) { //  spawns a monster in the cell
			Instantiate(Doodads[1], new Vector3(next.position.x, next.position.y + .5f, next.position.z + 0.25f), transform.rotation);		
		}
		if (Random.Range (0, 100) < weaponspawnrate) { // spawns ammo in the cell
			Instantiate(Doodads[2], new Vector3(next.position.x, next.position.y + .75f, next.position.z - 0.25f), transform.rotation);		
		}
		// We add this 'next' transform to the Set our function.
		AddToSet(next);
		// Recursively call this function as soon as it finishes.
		Invoke("FindNext", 0);
	}

	/*
	 * handles level restart events
	 */
	void Update() {

		// reloads a new level one level higher
		if (levelstart == true) {
			Level++;
			Application.LoadLevel(0);	
		}

		if (HUDManager.health <= 0 && HUDManager.restart == true) {
			HUDManager.dead = false;
			Level = 1;
			HUDManager.health = 100;
			HUDManager.arrows = 1;
			HUDManager.fuel = 30;
			HUDManager.Score = 0;
			Application.LoadLevel(0);
			HUDManager.restart = false;
			HUDManager.isPause = false;
		}
	}
}
